baseURL = "https://knockmitten.com/"
languageCode = "ja"
title = "knock mitten"
[Author]
    name = "Yuta Kurotaki"
[params]
    greeting = "knock mitten🥊"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/kurotaky"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://www.facebook.com/kurotaky"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:yuta.kurotaki@gmail.com"
